### ISSUE TITLE
Sensor does not restart properly after being disconnected

### ISSUE THREAD

**Issue by billtubbs** [adafruit/Adafruit_CircuitPython_BH1750#5]
I noticed with this sensor, that if you disconnect the sensor from the Qwiic cable while a script is running and then reconnect it, the measurements after reconnecting it are zero.  Here is my test script:

```Python
# Test BH1750 sensor

import board
import busio
from adafruit_bh1750 import BH1750
import time

i2c = busio.I2C(board.SCL, board.SDA)
addresses = i2c.scan()
bh1750 = BH1750(i2c)

while True:
    try:
        print(bh1750.lux)
    except OSError:
        print("Connection lost")
    time.sleep(1)
```

Output:
```text
49.16666666666667
49.16666666666667
49.16666666666667
19.583333333333336
39.16666666666667
45.41666666666667
49.583333333333336
Connection lost
Connection lost
Connection lost
Connection lost
0.0
0.0
0.0
0.0
0.0
```

With other Adafruit sensors (e.g. TMP117 and BME280), this does not occur.  Once reconnected the sensors continue to measure correctly.

Is this a bug or a hardware issue?

**Comment by ladyada** [comment]
once disconnected the sensor needs to be initialized. please note i2c is *not* a hot swap protocol, and is not guaranteed to recover from hot swapping

**Comment by billtubbs** [comment]
Thanks. By 'initialized' do you mean I have to re-instantiate the connection:

```python
bh1750 = adafruit_bh1750.BH1750(i2c)
```

Is there a way to detect that there has been a connection problem (Other than checking if the value is continually 0)?

Seems like this would be necessary in a reliable IoT logging system.

**Comment by ladyada** [comment]
you will have to write the code to manage this failure mode

**Comment by billtubbs** [comment]
Yes. That is exactly what I am trying to do and I can't figure out the method or statement to detect when the sensor has got into this state where it is not providing valid data but also not raising an error and needs to be re-started.  How do I do that?

[ Hopefully no vampires are using this sensor to decide if it is safe to go out! ]

**Comment by FoamyGuy** [comment]
@billtubbs maybe try to change that code so that as soon as you catch the OSError you no longer keep trying to read the lux value. Instead try to re-initialize the sensor. If it's not been re-connected yet then I think initialization will fail, you could catch the exception for that as well and then wait some time and try again in a loop until the initialization succeeds, then you can start trying to get lux readings again.

This way you never need to discern between a good reading and one coming from this bad state. Since the OSError tells you the connection was broken you know that future attempts to read `lux` without re-initializing will fail, so may as well stop trying to read and instead start re-trying the initialization.

**Comment by billtubbs** [comment]
I may not necessarily have an OSError if the connection issue is shorter than my sampling rate.  Once the device is reconnected it goes away and `bh1750.lux` returns the 0 value with no error.  That is the problem I am reporting here. Ideally the sensor and/or app should not be able to get into a state where it reports a false value without error.

**Comment by FoamyGuy** [comment]
You could re-write the loop to use `time.monotonic()` to keep track of time and decide when to take readings. This would let you avoid the usage of `time.sleep()` and therefore have a much quicker executing main loop, likely fast enough that you cannot unplug / re-plug fast enough to have the loop miss it. Once it's faster you could possible run an I2C scan during iterations where you don't take a reading so that your code can be aware when the disconnection happens.

**Comment by billtubbs** [comment]
Another option would be to give the object a 'status' attribute that tells you when something has gone wrong or when the reading is valid. Then, I could use that in my code to take whatever appropriate action is needed, e.g. reconnect.  

Sampling at a faster rate in the hope of detecting a rare and possibly non-existent problem is not a great solution.

**Comment by billtubbs** [comment]
Here is some of my actual code (above was a simplification to demonstrate the issue). This is for a remote monitoring application, which is why I need it to be reliable and as robust as possible.

```python
def read_sensor(device, attribute, bad=None):
    error = None
    try:
        reading = getattr(device, attribute)
    except Exception as err:
        reading = bad
        error = err
    return reading, error


def main():
    # Open I2C communication and connect to sensors
    i2c = busio.I2C(board.SCL, board.SDA)
    logger.info("I2C communication started.")
    devices = connect_to_devices(i2c, address_alloc, drivers)

...

        while True:
            now = datetime.now()
            timestamp = now.strftime("%Y-%m-%d %H:%M:%S")
            data = [('timestamp', f"'{timestamp}'")]
            for data_label, (device_description, attribute) in \
                                        sensor_readings.items():

...

                    device = devices[device_description]

...

                    try:
                        value, error = read_sensor(device, attribute, bad=None)
                    except Exception as err:
                        error = err
                    if error is None:
                        value_str = data_format[data_label][1].format(value)
                    else:
                        value_str = 'NULL'
                        logger.debug(f"Error reading from " \
                                      f"'{device_description}'.")
                        logger.debug(err, exc_info=True)
                data.append((data_label, value_str))
            t_elapsed = (datetime.now() - now).total_seconds()

...

            while now.second == datetime.now().second:
                pass
```
