### ISSUE TITLE
How to change the measurement mode? 

### ISSUE THREAD

**Issue by BehnamRosti** [adafruit/Adafruit_CircuitPython_BH1750#9]
With the default setting in this library, the maximum monitored lux is lower than 30,000 lx. Since BH1750 can capture up to 65535 lx, how to change the sensor configuration to LOW resolution for recording bright light?

**Comment by McNerdius** [comment]
```python
import adafruit_bh1750
from adafruit_bh1750 import Resolution

bh = adafruit_bh1750.BH1750(i2c)
bh.resolution = Resolution.LOW
```
^ works for me

**Comment by FoamyGuy** [comment]
I'm going to close this because @McNerdius has answered the specific question raised here. 

I did also think it would be nice to update the documentation pages to include more information about `resolution` (and `mode` incidentally) so I've created #11 to do that. Hopefully that will make it easier to discover how to use this feature moving forward.
